export const questions = [
  {
    id: "q01",
    prompt: "She ___ to school every day.",
    options: ["go", "goes", "going", "gone"],
    answer: 1,
    explain: "With he, she, and it, add -s in the present simple.",
  },
  {
    id: "q02",
    prompt: "They ___ football on Sundays.",
    options: ["plays", "play", "playing", "played"],
    answer: 1,
    explain: "With they, use the base verb in the present simple.",
  },
  {
    id: "q03",
    prompt: "He ___ like coffee.",
    options: ["don't", "doesn't", "isn't", "not"],
    answer: 1,
    explain: "Negative present simple for he/she/it: doesn't + base verb.",
  },
  {
    id: "q04",
    prompt: "___ your brother live in Kyiv?",
    options: ["Do", "Does", "Is", "Has"],
    answer: 1,
    explain: "Questions with he/she/it start with Does.",
  },
  {
    id: "q05",
    prompt: "Be quiet. The baby ___.",
    options: ["sleeps", "slept", "is sleeping", "sleep"],
    answer: 2,
    explain: "Use the present continuous for an action happening now.",
  },
  {
    id: "q06",
    prompt: "Look! The children ___ in the park.",
    options: ["play", "plays", "are playing", "played"],
    answer: 2,
    explain: "Look! signals an action in progress: are playing.",
  },
  {
    id: "q07",
    prompt: "I ___ a letter at the moment.",
    options: ["write", "am writing", "wrote", "have write"],
    answer: 1,
    explain: "At the moment means the action is happening now.",
  },
  {
    id: "q08",
    prompt: "We ___ a film yesterday evening.",
    options: ["watch", "watched", "watching", "have watch"],
    answer: 1,
    explain: "Yesterday evening needs the past simple.",
  },
  {
    id: "q09",
    prompt: "They ___ to Paris last summer.",
    options: ["go", "went", "gone", "have gone"],
    answer: 1,
    explain: "Last summer is a finished time, so use went.",
  },
  {
    id: "q10",
    prompt: "I ___ not at school yesterday.",
    options: ["were", "was", "am", "did"],
    answer: 1,
    explain: "The past of I am is I was.",
  },
  {
    id: "q11",
    prompt: "She ___ her homework last night.",
    options: ["don't do", "didn't", "didn't do", "doesn't do"],
    answer: 2,
    explain: "Past simple negative: didn't + base verb.",
  },
  {
    id: "q12",
    prompt: "I ___ my keys and I still can't find them.",
    options: ["lose", "lost", "have lost", "am losing"],
    answer: 2,
    explain: "Present perfect links a past action to the present result.",
  },
  {
    id: "q13",
    prompt: "She ___ finished her homework yet.",
    options: ["has", "hasn't", "didn't", "doesn't"],
    answer: 1,
    explain: "Yet in a negative sentence uses the present perfect: hasn't finished.",
  },
  {
    id: "q14",
    prompt: "I have ___ seen this film.",
    options: ["yet", "already", "ago", "since"],
    answer: 1,
    explain: "Already is used in positive present perfect sentences.",
  },
  {
    id: "q15",
    prompt: "Anna ___ in this class since September.",
    options: ["is", "was", "has been", "have been"],
    answer: 2,
    explain: "Since + a starting point uses the present perfect.",
  },
  {
    id: "q16",
    prompt: "We have lived here ___ five years.",
    options: ["since", "for", "ago", "during"],
    answer: 1,
    explain: "Use for with a period of time.",
  },
  {
    id: "q17",
    prompt: "If it rains, we ___ at home.",
    options: ["stay", "stayed", "will stay", "staying"],
    answer: 2,
    explain: "First conditional: if + present, will + base verb.",
  },
  {
    id: "q18",
    prompt: "I will call you when I ___ home.",
    options: ["get", "will get", "got", "getting"],
    answer: 0,
    explain: "After when, use the present simple for the future.",
  },
  {
    id: "q19",
    prompt: "Tomorrow I am going ___ my uncle.",
    options: ["visit", "to visit", "visiting", "visited"],
    answer: 1,
    explain: "going to + base verb talks about a plan.",
  },
  {
    id: "q20",
    prompt: "You ___ be quiet in the library.",
    options: ["can", "should", "would", "are"],
    answer: 1,
    explain: "Should gives advice or a mild rule.",
  },
  {
    id: "q21",
    prompt: "___ I borrow your pen?",
    options: ["Can", "Am", "Do", "Have"],
    answer: 0,
    explain: "Can I...? asks for permission.",
  },
  {
    id: "q22",
    prompt: "My sister is ___ than me.",
    options: ["tall", "taller", "tallest", "more tall"],
    answer: 1,
    explain: "Compare two people with the comparative: taller.",
  },
  {
    id: "q23",
    prompt: "This exercise is ___ than the last one.",
    options: ["easy", "easier", "easiest", "more easy"],
    answer: 1,
    explain: "Short adjectives take -er: easier.",
  },
  {
    id: "q24",
    prompt: "July is often the ___ month here.",
    options: ["hot", "hotter", "hottest", "most hot"],
    answer: 2,
    explain: "The superlative compares one thing with the whole group.",
  },
  {
    id: "q25",
    prompt: "She is ___ honest person.",
    options: ["a", "an", "the", "one"],
    answer: 1,
    explain: "Use an before a vowel sound. Honest starts with a silent h.",
  },
  {
    id: "q26",
    prompt: "___ moon looks bright tonight.",
    options: ["A", "An", "The", "—"],
    answer: 2,
    explain: "Use the when there is only one of something.",
  },
  {
    id: "q27",
    prompt: "There isn't ___ milk in the fridge.",
    options: ["some", "any", "many", "a few"],
    answer: 1,
    explain: "Use any in negative sentences.",
  },
  {
    id: "q28",
    prompt: "How ___ apples do you want?",
    options: ["much", "many", "a lot", "little"],
    answer: 1,
    explain: "Apples are countable, so use many.",
  },
  {
    id: "q29",
    prompt: "How ___ time do we have?",
    options: ["many", "much", "few", "a few"],
    answer: 1,
    explain: "Time is uncountable here, so use much.",
  },
  {
    id: "q30",
    prompt: "There is only ___ water left.",
    options: ["a few", "a little", "many", "several"],
    answer: 1,
    explain: "A little is for a small amount of an uncountable noun.",
  },
  {
    id: "q31",
    prompt: "I have ___ close friends in this city.",
    options: ["a little", "much", "a few", "any"],
    answer: 2,
    explain: "A few is for a small number of countable nouns.",
  },
  {
    id: "q32",
    prompt: "There ___ two books on the desk.",
    options: ["is", "are", "be", "was"],
    answer: 1,
    explain: "Two books is plural, so use are.",
  },
  {
    id: "q33",
    prompt: "The keys are ___ my bag.",
    options: ["on", "in", "at", "to"],
    answer: 1,
    explain: "Something inside a bag is in it.",
  },
  {
    id: "q34",
    prompt: "I wake up ___ 7 o'clock.",
    options: ["in", "on", "at", "by"],
    answer: 2,
    explain: "Use at with clock times.",
  },
  {
    id: "q35",
    prompt: "The lesson is ___ Monday.",
    options: ["in", "on", "at", "to"],
    answer: 1,
    explain: "Use on with days.",
  },
  {
    id: "q36",
    prompt: "We have English ___ the morning.",
    options: ["in", "on", "at", "by"],
    answer: 0,
    explain: "Use in with parts of the day: in the morning.",
  },
  {
    id: "q37",
    prompt: "I go to school ___ bus.",
    options: ["by", "on", "with", "in"],
    answer: 0,
    explain: "Use by with a means of transport: by bus.",
  },
  {
    id: "q38",
    prompt: "She is good ___ maths.",
    options: ["in", "on", "at", "for"],
    answer: 2,
    explain: "The pattern is good at + a subject or skill.",
  },
  {
    id: "q39",
    prompt: "I am looking ___ my keys.",
    options: ["for", "after", "at", "on"],
    answer: 0,
    explain: "Look for means to try to find something.",
  },
  {
    id: "q40",
    prompt: "Please turn ___ the light. It is dark.",
    options: ["on", "off", "out", "down"],
    answer: 0,
    explain: "Turn on means to start a light or machine.",
  },
  {
    id: "q41",
    prompt: "I am ___ in music.",
    options: ["interesting", "interested", "interest", "interests"],
    answer: 1,
    explain: "A person is interested in something.",
  },
  {
    id: "q42",
    prompt: "She speaks English very ___.",
    options: ["good", "well", "nice", "fluent"],
    answer: 1,
    explain: "Well is the adverb. It describes how she speaks.",
  },
  {
    id: "q43",
    prompt: "I enjoy ___ English stories.",
    options: ["read", "to read", "reading", "reads"],
    answer: 2,
    explain: "Enjoy is followed by the -ing form.",
  },
  {
    id: "q44",
    prompt: "She asked me ___ her with the bags.",
    options: ["help", "to help", "helping", "helped"],
    answer: 1,
    explain: "Ask someone to do something.",
  },
  {
    id: "q45",
    prompt: "The girl ___ sits next to me is my friend.",
    options: ["who", "which", "whose", "what"],
    answer: 0,
    explain: "Use who for people.",
  },
  {
    id: "q46",
    prompt: "A person who teaches at school is a ___.",
    options: ["teacher", "student", "doctor", "driver"],
    answer: 0,
    explain: "A teacher is a person who teaches.",
  },
  {
    id: "q47",
    prompt: "To take something and later give it back is to ___.",
    options: ["borrow", "lend", "keep", "spend"],
    answer: 0,
    explain: "You borrow something from another person.",
  },
  {
    id: "q48",
    prompt: "The opposite of cheap is ___.",
    options: ["expensive", "poor", "small", "fast"],
    answer: 0,
    explain: "Expensive means costing a lot of money.",
  },
  {
    id: "q49",
    prompt: "The past form of buy is ___.",
    options: ["buyed", "bought", "brought", "buying"],
    answer: 1,
    explain: "Buy is irregular: buy, bought, bought.",
  },
  {
    id: "q50",
    prompt: "Could you speak more ___, please?",
    options: ["slow", "slowly", "slower", "slowest"],
    answer: 1,
    explain: "Slowly is the adverb. It describes the verb speak.",
  },
];
